### PR TITLE
Add various Plants, Flowers, etc.

### PR DESCRIPTION
**Pull request by CREEATION**

### CODE REVIEW

**Comment by eiszfuchs** [comment]
Good morning @CREEATION, and thanks for your contribution!

I'll merge all this right away, do you want to add yourself to the list if contributors by yourself or want me to add you? 🤳

**Comment by CREEATION** [comment]
Forgot: **+ Double Grass**

It'd be _lit_ if you could add me 👍

**Comment by eiszfuchs** [comment]
Alright, how/under which name do you want to appear in the list?

**Comment by eiszfuchs** [comment]
Oh, I see you've added a new block texture for flower pots, too. Do you think you are able to fit the flower pot model into the new resolution, too? 👍

**Comment by CREEATION** [comment]
> Do you think you are able to fit the flower pot model into the new resolution, too? 👍

Nope!

> Alright, how/under which name do you want to appear in the list?

Thomas "CREEATION"

**Comment by eiszfuchs** [comment]
Done! Did it!

Congrats! You are a Contributor!

**Pull request merged**
